### ISSUE TITLE
Returned values aren't valid - with new Aragon DAO

### ISSUE THREAD

**Issue by wslyvh** [my-dao-dashboard/My-DAO-Dashboard#1]
**Describe the issue**
Getting errors when trying to retrieve a newly created Aragon DAO; Returned values aren't valid.
Possibly related to v0.8 Aragon upgrade.
OR because of different voting (e.g. Kernel, ACL) types. Right now we only parse Minting or Token types.

**Steps to Reproduce**

1. Go to the dashboard, with any account.
2. In settings; Add the following address: 0x3917d5Db38879BAb97Cb5B65eC5562F4CF648196
3. Go back to the dashboard & refresh.

**Expected behavior**
Should show the overview of your DAO's.

**Actual behavior**
Dashboard remains stuck at "Loading DAO's..". 
But an error is shown on the console window.

**Environment**

- Network (e.g. mainnet, rinkeby, private): mainnet
- DAO you're trying to work with (e.g. `MolochDAO` or `DAOstack`): Aragon 0.8
https://mainnet.aragon.org/#/amigoz/home
-or- address
0xDc5C7527c4Ef325c4d9D08A02f80519a7FbDC217 

**Additional data**

![image](https://user-images.githubusercontent.com/25974464/64907470-2b198300-d6f3-11e9-84f6-abc4cc3e0cc6.png)

**Comment by wslyvh** [comment]
This was not related to any Aragon App - or upgrades.

But by querying each token from the account balance, to check if it is an Aragon DAO. 
Some tokens seem incompatible. 
Need to further debug this, but for now, just skipping the 'invalid' tokens.

**Comment by ukstv** [comment]
Some of the tokens naively considered as Aragon ones are really something else. The one mentioned above is District0x, for example. Try-catch approach seems perfectly valid here. Gonna beautify it a bit. This should be done anyway, as current dao service thing is copied mainly from quick and dirty hackathon times.
